services:  
  proxy:
    image: nginx:latest
    ports:
    - 80:80
    depends_on:
      - database
  
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data


volumes:
  postgres_data: